### ISSUE TITLE
Problem with revised warrior HLAs (bugged names/descriptions)

### ISSUE THREAD

**Issue by rahenry** [BartyMae/SR_Revised#12]
This component appears to give incorrect names and descriptions to the affected abilities (WW, GWW and hardiness). They are given the names Paw, Paw, and Cat, and some similarly random descriptions. This does not occur with SRbeta18. This is using a fresh BG2EE install. The abilities appear to still work correctly. Other spells and abilities appear to be entirely correct when installing SR (I have tested both with and without the other components), although I have not checked everything.

I also note that I'm installing on Linux in a case-insensitive partition. I don't think this is the cause of the issue as everything else works correctly, but it might be.

[weidu.log](https://github.com/BartyMae/SR_Revised/files/4391340/weidu.log)

**Comment by BartyMae** [comment]
I am really bad at noticing issues being opened up on here. Thanks, will fix within the next 24 hours hopefully.

**Comment by BartyMae** [comment]
Okay, should now be fixed. Thanks very much!

**Comment by rahenry** [comment]
Great job, thank you!
