### ISSUE TITLE
ASSERTION FAILED with new IRR .201 version

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#15]
Hi Bartimaeus,

Right after Gorion cutscene, game CTD and "baldur.err" reports:

_ASSERTION FAILED!
File: ChVidImage3d.cpp
Line: 899

Exp: FALSE

Msg: no msg.
Run Debugger?_

WeiDU is very lean:

TOBEX/TOBEX.TP2 #0 #100 // TobEx - Core: v28
BG2FIXPACK/SETUP-BG2FIXPACK.TP2 #0 #0 // BG2 Fixpack - Core Fixes: v13
BG2FIXPACK/SETUP-BG2FIXPACK.TP2 #0 #3 // BETA Core Fixes (please check the readme!): v13
1PP/1PP.TP2 #0 #101 // 1ppv4: Core paperdolls
1PP/1PP.TP2 #0 #103 // 1ppv4: Extended palette entries -> Full install (recommended)
1PP/1PP.TP2 #0 #104 // 1ppv4: GUI additions for BGII
1PP/1PP.TP2 #0 #200 // 1ppv4: Core content patches
1PP/1PP.TP2 #0 #400 // 1ppv4: Core updates and item patches
BGT/BGT.TP2 #0 #0 // Baldur's Gate Trilogy - Core: v1.21
ITEM_REV/ITEM_REV.TP2 #0 #0 // Item Revisions by Demivrgvs: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #1030 // Store Revisions: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #10 // Revised Shield Bonuses: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #17 // Weapon Changes: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #11 // Dual Wielding Changes for Light and Heavy Weapons: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #19 // Revised Backstabbing -> More Weapons Usable for Backstabbing: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #1200 // Revised Critical Hit Aversion: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #12 // Items of Protection Can Be Worn with Magical Armor: V4 Beta 10 (Revised V1.3.201)
ITEM_REV/ITEM_REV.TP2 #0 #15 // PnP Equipment for Druids -> Druids Only: V4 Beta 10 (Revised V1.3.201)
SPELL_REV/SETUP-SPELL_REV.TP2 #0 #0 // Spell Revisions: v4 Beta 18 (Revised V1.3.200)
SPELL_REV/SETUP-SPELL_REV.TP2 #0 #20 // Mirror Image Fix: v4 Beta 18 (Revised V1.3.200)
SPELL_REV/SETUP-SPELL_REV.TP2 #0 #30 // Dispel Magic Fix: v4 Beta 18 (Revised V1.3.200)
SPELL_REV/SETUP-SPELL_REV.TP2 #0 #55 // Spell Deflection blocks AoE spells: v4 Beta 18 (Revised V1.3.200)
SPELL_REV/SETUP-SPELL_REV.TP2 #0 #60 // Update Spellbooks of Joinable NPCs: v4 Beta 18 (Revised V1.3.200)
AURORA/SETUP-AURORA.TP2 #0 #40 // Shorten Gorion battle cutscene: v5.2.1
AURORA/SETUP-AURORA.TP2 #0 #9000 // Fix area creature references: v5.2.1
STRATAGEMS/SETUP-STRATAGEMS.TP2 #0 #4146 // Skip the Candlekeep tutorial sections -> Skip Candlekeep altogether (warning: breaks the 4th wall!): v33.4

**Comment by ChitownWillie** [comment]
Narrowed it down to IRR.

Working WeiDU:

~TOBEX/TOBEX.TP2~ #0 #100 // TobEx - Core: v28
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #3 // BETA Core Fixes (please check the readme!): v13
~BGT/BGT.TP2~ #0 #0 // Baldur's Gate Trilogy - Core: v1.21
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #0 // Item Revisions by Demivrgvs: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #1030 // Store Revisions: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #10 // Revised Shield Bonuses: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #17 // Weapon Changes: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #11 // Dual Wielding Changes for Light and Heavy Weapons: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #19 // Revised Backstabbing -> More Weapons Usable for Backstabbing: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #1200 // Revised Critical Hit Aversion: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #12 // Items of Protection Can Be Worn with Magical Armor: V4 Beta 10 (Revised V1.3.201)
// Recently Uninstalled: ~ITEM_REV/ITEM_REV.TP2~ #0 #15 // PnP Equipment for Druids -> Druids Only: V4 Beta 10 (Revised V1.3.201)
~AURORA/SETUP-AURORA.TP2~ #0 #40 // Shorten Gorion battle cutscene: v5.2.1
~AURORA/SETUP-AURORA.TP2~ #0 #9000 // Fix area creature references: v5.2.1
~STRATAGEMS/SETUP-STRATAGEMS.TP2~ #0 #4146 // Skip the Candlekeep tutorial sections -> Skip Candlekeep altogether (warning: breaks the 4th wall!): v33.4

**Comment by ChitownWillie** [comment]
I think the main component is breaking it.

Latest error message:

ASSERTION FAILED!
File: ChVidImage.cpp
Line: 1921

Exp: FALSE

Msg: .BAM is corrupted (GetFrame() failed)
Run Debugger?

With only main component:

TOBEX/TOBEX.TP2 #0 #100 // TobEx - Core: v28
BG2FIXPACK/SETUP-BG2FIXPACK.TP2 #0 #0 // BG2 Fixpack - Core Fixes: v13
BG2FIXPACK/SETUP-BG2FIXPACK.TP2 #0 #3 // BETA Core Fixes (please check the readme!): v13
BGT/BGT.TP2 #0 #0 // Baldur's Gate Trilogy - Core: v1.21
AURORA/SETUP-AURORA.TP2 #0 #40 // Shorten Gorion battle cutscene: v5.2.1
AURORA/SETUP-AURORA.TP2 #0 #9000 // Fix area creature references: v5.2.1
STRATAGEMS/SETUP-STRATAGEMS.TP2 #0 #4146 // Skip the Candlekeep tutorial sections -> Skip Candlekeep altogether (warning: breaks the 4th wall!): v33.4
ITEM_REV/ITEM_REV.TP2 #0 #0 // Item Revisions by Demivrgvs: V4 Beta 10 (Revised V1.3.201)

**Comment by ChitownWillie** [comment]
Looks like it got fixed w/ IRR .204.

Thanks!

**Comment by BartyMae** [comment]
Sorry about that - also, I didn't even see these until I already fixed it. Someone else who also doesn't like to use the main 1pp components reported a couple of problems with the new graphics-patching system that I didn't properly gate behind 1pp checks.
