### ISSUE TITLE
"Halt Undead" is broken

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#17]
Noticed this post from 2018 on Gibblerings3:

"Halt Undead and Control Undead are affected by magic resistance. Doesn't that make them kind of...useless? Not sure if bug or just absolutely terrible spells. Lower Resistance does exist, yes, but...these spells are specifically for targeting the undead, and many undead have way too high of spell resistance to effectively be combated by Lower Resistance."

Seems like still an issue - Repeated attempts on a skeleton in High Hedge didn't work.

**Comment by BartyMae** [comment]
https://www.gibberlings3.net/forums/topic/29618-sr-revised-v13200-2020-august-22nd/page/73/?tab=comments#comment-292139

Can't confirm at this time.

**Comment by BartyMae** [comment]
Closing since no response has been given for two weeks.
