### ISSUE TITLE
Bats from "Animal Summoning" are broken

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#18]
Bonus to hit are squirrely:

![image](https://user-images.githubusercontent.com/65503897/110240836-6923eb80-7f13-11eb-98a5-88a6095c5f52.png)

**Comment by BartyMae** [comment]
I forgot to close this - this was fixed in https://github.com/BartyMae/SR_Revised/commit/c699d08fa0fae3043a3f993d297987ddb8d398f7.

**Comment by ChitownWillie** [comment]
Thank you.
