### ISSUE TITLE
Bats from "Animal Summoning I" still overpowered

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#19]
Testing with "Spell Revisions: v4 Beta 18 (Revised V1.3.500)"  - Note the +12 THAC0:

![image](https://user-images.githubusercontent.com/65503897/121717381-b8dff900-caa6-11eb-9b2a-308312569a13.png)

**Comment by ChitownWillie** [comment]
Is there a way I can turn off/deactivate the "Swarm" feature to see if that is the culprit?

**Comment by BartyMae** [comment]
It is the culprit. There seems to be an issue of the specific aura opcode used for this effect inexplicably double, triple, quadruple, even quintuple and beyond applying itself, see here: https://www.gibberlings3.net/forums/topic/32826-opcode-272-apply-effect-on-condition/

**Comment by ChitownWillie** [comment]
Thanks Bartimaeus.

Would removing Effect 1 (Type: Use EFF file on condition)  and Effect 7
(Base THAC0 bonus) in BATSU.ITM do the trick?

[image: image.png]

**Comment by BartyMae** [comment]
It would.

**Comment by BartyMae** [comment]
More or less resolved as of https://github.com/BartyMae/SR_Revised/commit/04829d3bfea74a400c69b06090280a9b9eff6591.

It's still not by any means perfect, but it should prevent looney tunes-level of stacking.
