### ISSUE TITLE
Faerie Fire range

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#21]
Actual range = 20':

![image](https://user-images.githubusercontent.com/65503897/148103281-5891c17e-2e17-45be-b934-ddadd5c084e7.png)

But description reads 10':

![image](https://user-images.githubusercontent.com/65503897/148103326-19bb3b2b-2fff-4678-b33a-a8756d93cce0.png)

**Comment by BartyMae** [comment]
Fixed, thanks!
