### ISSUE TITLE
Tenser's transformation scaling bug

### ISSUE THREAD

**Issue by BlackTalons** [BartyMae/SR_Revised#22]
Using Tenser's transformation with version 1.3.900 of the mod installed in BG2EE always works as if casted by a lvl 12 character, in regards to bonus hp, base thac0 and bonus APR.

Examples: Create a new Mage character in BGEEII, spawn the scroll with Ctrl+Space->C:CreateItem("scrl7g"), learn the scroll, manually level up the character to lvl 12 by giving him 750000 xp in order to cast the spell. The character gains 24 hp, 0.5 APR, base thac0 9, -2 thac0 bonus and -4 AC bonus and +2 damage as expected.
Further leveling the character to lvl 14 and casting the spell again results in the same exact increase: +24 hp, +0.5 APR, base thac0 set to 9, rest of bonuses as expected.

Create a sorcerer character in ToB and select Tenser's Transformation as one of the 6th lvl spells. Casting the spell with a lvl 16 sorcerer results again in increases corresponding to lvl 12. Maxing out xp at 8M, achieving lvl 31 and casting the spell still results in the equivalent to a lvl 12 cast. Casting BBoD afterwards fails to change the base thac0, despite setting it to 0 when casted alone.

No other mods were present. This was tested on a clean 2.6.6.0 install.

**Comment by BartyMae** [comment]
@BlackTalons Thanks, will take a look into it and update.

**Comment by BartyMae** [comment]
It only took an eternity to remember and fix, but it has now been fixed in the latest repository version as of [V1.3.956](https://github.com/BartyMae/SR_Revised/commit/80f26d53d85a19af7b8292e8b1b2f5fd8085d74c). Thank you!
