### ISSUE TITLE
Non-spell sources of effects

### ISSUE THREAD

**Issue by gatperdut** [BartyMae/SR_Revised#23]
Hi! kind of a question/issue I had with SR: does stuff that behaves like a spell but isn't in a spellbook, like the Inquisitor's Dispel Magic/True Vision, or that Gem of Seeing, or the Axe that allows to cast Dispel Magic, behave like the SRR spells?

**Comment by BartyMae** [comment]
For innate player class abilities (like your mentioned Dispel Magic and True Seeing), the answer should be generally yes. For item abilities, it will depend. If the items actually have your characters cast the spellbook spells, then yes...if the items instead cast some other resource that is like but not actually the spell, then no. IRR items do cast SRR spells.

P.S. Issues and questions should generally be posted about in the G3 forum thread if possible: you'll get much more prompt answers than here.
