### ISSUE TITLE
BG1EE String issues with some spells

### ISSUE THREAD

**Issue by Doomathon** [BartyMae/SR_Revised#24]
### Expected behavior:
With the default settings.ini option for petrification, when a basilisk attempts to petrify a target, and the name of the spell shows in the combat log, it should display "Flesh to Stone" in BG1EE (without SoD, in the event that it would make a difference), like it does in BG2EE.

### Observed behavior:
The combat log is filled with unrelated nonsense. I specifically observed the identified description for the Nymph Cloak suddenly appearing in the combat log.

### Other notes
This appears to be entirely due to BG1EE's String Refs in the dialog.tlk for names of spells common in both games being different between the two games.

For example, from a peak at Near Infinity, the string id 34648 in BG2EE refers to the string "Flesh to Stone" used for the applicable spell name. In BG1EE, that same string ID is invalid, because it is outside the vanilla string table. The BG1EE string ID for "Flesh to Stone" appears to be 26030, based on the name string ID on the vanilla BG1EE Mage Flesh to Stone Spell (SPWI604.SPL)

I haven't exhaustively checked every single spell modified by SRR, so there easily could be other examples (that may or may not end up visible in game to a player) when installed on BG1EE, but that one I definitely noticed while fighting Mutamin's basilisks.

Edit: Slight edit for grammar.

**Comment by BartyMae** [comment]
Thanks, will fix. BG1EE having wrong strings for spell effects has been an ongoing project for a while, owing to the fact that SR (and IR) was designed for BG2.

**Comment by BartyMae** [comment]
Whoops, totally forgot about this - should now be resolved. Thank you!
